#!/bin/bash

if [[ -z $1 ]]; then
	echo "specify file name"
	exit 1
fi

pathToUntrash=""
nameInTrash=""

IFS=$'\n'
for line in $(cat ~/.trash.log); do

	path=$(echo $line | awk '{print $1}')
	name=$(echo $line | awk '{print $2}')
	

	if [ $(basename $path) != $1 ]; then
		continue
	fi
	echo "This one? [y/n] $path"
	read ans
	if [[ $ans = "y" ]]; then
		pathToUntrash=$path
		nameInTrash=$name
		break
	fi
done

if [[ -z $pathToUntrash ]]; then
	echo "Couldn't find your file"
	exit 2
fi

if [ ! -d $(dirname $pathToUntrash) ]; then
	echo "Untrash dir does not exist $pathToUntrash"
	pathToUntrash="$HOME/$(basename $pathToUntrash)"
fi

while ([ -d $pathToUntrash ] || [ -f $pathToUntrash ]); do
	pathToUntrash="$pathToUntrash"1
done

ln ~/trash/$nameInTrash $pathToUntrash 2>/dev/null ||
{
	echo "couldn't restore, unknown error"
	exit 3
}

rm -- ~/trash/$nameInTrash

content=$(cat ~/.trash.log | grep -Ev -- "$nameInTrash")

printf "$content\n" > ~/.trash.log
echo "restored at path $pathToUntrash"
